import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { getCampaign } from '../api/client'

export default function EmailPreview() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [campaign, setCampaign] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getCampaign(id)
      .then((res) => setCampaign(res.data))
      .finally(() => setLoading(false))
  }, [id])

  if (loading) return (
    <div className="flex items-center justify-center py-32">
      <svg className="animate-spin w-8 h-8 text-blue-600" fill="none" viewBox="0 0 24 24">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/>
      </svg>
    </div>
  )
  if (!campaign) return null

  const email = campaign.email_json || {}

  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-blue-600 text-sm font-medium mb-4">
        <button onClick={() => navigate('/')} className="hover:underline">Dashboard</button>
        <span>/</span>
        <button onClick={() => navigate(`/campaign/${id}/preview`)} className="hover:underline">Campaign #{id}</button>
        <span>/</span>
        <span>Email Preview</span>
      </div>

      <h1 className="text-2xl font-bold text-gray-900 mb-6">Email Preview — Content Agent Output</h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Email Renderer */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            {/* Email Client Toolbar */}
            <div className="bg-gray-100 border-b border-gray-200 px-5 py-3 flex items-center gap-2">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-red-400"/>
                <div className="w-3 h-3 rounded-full bg-yellow-400"/>
                <div className="w-3 h-3 rounded-full bg-green-400"/>
              </div>
              <p className="text-xs text-gray-500 ml-2 font-medium">Email Preview</p>
            </div>
            {/* Email Content */}
            <div className="p-6">
              <div className="border-b border-gray-100 pb-4 mb-4">
                <p className="text-xs text-gray-400 font-medium uppercase tracking-wide">Subject</p>
                <p className="text-base font-bold text-gray-900 mt-1">{email.subject_line || '—'}</p>
              </div>
              <div className="prose prose-sm max-w-none text-gray-700 leading-relaxed whitespace-pre-wrap text-sm">
                {email.email_body || '—'}
              </div>
              {email.cta_text && (
                <div className="mt-6">
                  <button className="bg-blue-700 text-white text-sm font-semibold px-8 py-3 rounded-lg shadow">
                    {email.cta_text}
                  </button>
                </div>
              )}
              {email.disclaimer && (
                <div className="mt-6 pt-4 border-t border-gray-100">
                  <p className="text-xs text-gray-400 leading-relaxed">{email.disclaimer}</p>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Sidebar: Field Breakdown */}
        <div className="space-y-4">
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-4">Email Fields</p>
            <div className="space-y-4">
              <FieldBox label="Subject Line" value={email.subject_line} />
              <FieldBox label="CTA Text" value={email.cta_text} highlight />
              <div>
                <p className="text-xs font-semibold text-gray-500 mb-1">Email Body</p>
                <p className="text-xs text-gray-500">{(email.email_body || '').split(' ').length} words</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-gray-500 mb-1">Disclaimer</p>
                <p className="text-xs text-gray-500 italic">{email.disclaimer ? 'Present' : 'Missing'}</p>
              </div>
            </div>
          </div>

          <div className="bg-green-50 border border-green-200 rounded-xl p-4">
            <p className="text-xs font-semibold text-green-700 mb-2">Content Agent</p>
            <p className="text-xs text-green-700">
              This email was generated by the Content Agent using the campaign strategy as input.
              It has been reviewed by the Compliance Agent for BFSI regulatory adherence.
            </p>
          </div>

          <button
            onClick={() => navigate(`/campaign/${id}/approve`)}
            className="w-full bg-blue-700 hover:bg-blue-800 text-white text-sm font-semibold py-3 rounded-xl transition"
          >
            Proceed to Approval
          </button>
        </div>
      </div>
    </div>
  )
}

function FieldBox({ label, value, highlight }) {
  return (
    <div>
      <p className="text-xs font-semibold text-gray-500 mb-1">{label}</p>
      <p className={`text-xs rounded px-2 py-1.5 ${highlight ? 'bg-blue-50 text-blue-700 font-medium' : 'text-gray-700'}`}>
        {value || '—'}
      </p>
    </div>
  )
}
